### ISSUE TITLE
onError is not a function

### ISSUE THREAD

**Issue by Natteke** [arkpow1/errity#3]
Hello!

I'm trying to use errity with a synchronous function and config, but I'm getting an error that onError is not defined. Am I doing something wrong?

Code
```
import "./styles.css";
import { errity } from "errity";

window.cb = errity(
  () => {
    throw 123;
  },
  {
    onRetryError: 1,
    retryDelay: 1000,
    onError: console.log,
  }
);

```

[Example on codesandbox](https://codesandbox.io/p/sandbox/priceless-blackburn-jk88rp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxdponwg00063b6nvcl1xtki%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxdponwg00023b6nahr6cba8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxdponwg00033b6nmf3gwpdn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxdponwg00053b6nsz1vhwv8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxdponwg00023b6nahr6cba8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdponwf00013b6n1goce99f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clxdponwg00023b6nahr6cba8%2522%252C%2522activeTabId%2522%253A%2522clxdponwf00013b6n1goce99f%2522%257D%252C%2522clxdponwg00053b6nsz1vhwv8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdponwg00043b6nc2de5kcj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxdponwg00053b6nsz1vhwv8%2522%252C%2522activeTabId%2522%253A%2522clxdponwg00043b6nc2de5kcj%2522%257D%252C%2522clxdponwg00033b6nmf3gwpdn%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxdponwg00033b6nmf3gwpdn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by arkpow1** [comment]
You need to install the latest version of the package 😉
